# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker volume create dbdata

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker-compose -f docker-compose.prod.yaml up -d --build

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker logs -f --tail 100 app 

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker exec -t app cat .docker/entrypoint.prod.sh

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker exec -t app php /var/www/vendor/bin/phpunit -c /var/www/phpunit.xml