# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker-compose -f docker-compose.prod.yaml up -d

- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker exec -t app ls /var/www/vendor/bin


- task: Bash@3
  inputs:
   targetType: 'inline'
   script: docker exec -t app php /var/www/vendor/bin/phpunit -c /var/www/phpunit.xml