version: '3'

services:
    app:
        build: .
        container_name: apinav-app
        entrypoint: dockerize ./.docker/entrypoint.sh
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network

    nginx:
        build: .docker/nginx
        container_name: apinav-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
