version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: app
        environment: 
            - DEPLOY_ENV=staging
        volumes: 
            - /var/www
        depends_on:
            - db
    
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: db
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=*secret12345