version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: app
        entrypoint: dockerize -wait tcp://db:1433 -timeout 40s ./.docker/entrypoint.prod.sh
        environment: 
            - DEPLOY_ENV=staging
        volumes: 
            - /var/www
        depends_on:
            - db

    db:
        build: ./.docker/sqlserver
        container_name: db
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=*secret12345
            - MSSQL_PID=Standard