version: '3'

services:
    app:
        build: .
        container_name: apinav-app
        entrypoint: dockerize -wait tcp://db:1433 -timeout 40s ./.docker/entrypoint.dev.sh
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    nginx:
        build: .docker/nginx
        container_name: apinav-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        depends_on:
            - app
    
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: apinav-db
        entrypoint: ./.docker/sqlserver/entrypoint.sh
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=*secret12345
        volumes: 
            - apinav-db:/var/opt/mssql    

volumes:
    apinav-db:
        external: true