version: '3'

services:
    app:
        image: laravel-test:latest
        environment:
          - APP_NAME=Laravel
          - APP_ENV=local
          - APP_KEY=base64:JTD9K5unT0N+riES0Xm3RevxxsQGXZWNVdKup+ijfVk=
          - APP_DEBUG=true
          - APP_URL=http://localhost
          - DB_CONNECTION=mysql
          - DB_HOST=laravel-test.mysql.database.azure.com
          - DB_PORT=3306
          - DB_DATABASE=laravel-test
          - DB_USERNAME=root_test@laravel-test
          - DB_PASSWORD=Secret12345
